/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary": "#006a62",
        "on-primary": "#ffffff",
        "primary-fixed": "#84f5e8",
        "primary-fixed-dim": "#66d9cc",
        "on-primary-fixed": "#00201d",
        "on-primary-fixed-variant": "#005049",
        "primary-container": "#26a69a",
        "on-primary-container": "#003430",
        "secondary": "#306576",
        "on-secondary": "#ffffff",
        "secondary-container": "#b3e8fb",
        "on-secondary-container": "#34697a",
        "secondary-fixed": "#b6ebfe",
        "secondary-fixed-dim": "#9acee1",
        "on-secondary-fixed": "#001f28",
        "on-secondary-fixed-variant": "#114d5d",
        "tertiary": "#006972",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#3ca2ae",
        "on-tertiary-container": "#003338",
        "tertiary-fixed": "#92f1fe",
        "tertiary-fixed-dim": "#75d5e2",
        "on-tertiary-fixed": "#001f23",
        "on-tertiary-fixed-variant": "#004f56",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "background": "#f7f9ff",
        "on-background": "#0b1d2d",
        "surface": "#f7f9ff",
        "on-surface": "#0b1d2d",
        "on-surface-variant": "#3d4947",
        "surface-bright": "#f7f9ff",
        "surface-dim": "#cadcf2",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#edf4ff",
        "surface-container": "#e3efff",
        "surface-container-high": "#d9eaff",
        "surface-container-highest": "#d2e4fb",
        "surface-variant": "#d2e4fb",
        "surface-tint": "#006a62",
        "outline": "#6d7a77",
        "outline-variant": "#bcc9c6",
        "inverse-surface": "#213243",
        "inverse-on-surface": "#e8f1ff",
        "inverse-primary": "#66d9cc",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "8px",
        sm: "12px",
        md: "20px",
        lg: "32px",
        xl: "48px",
        gutter: "24px",
        unit: "4px",
        margin: "24px",
      },
      fontFamily: {
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "body-lg": ["Public Sans", "sans-serif"],
        "body-base": ["Public Sans", "sans-serif"],
        "label-bold": ["Public Sans", "sans-serif"],
        caption: ["Public Sans", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-base": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "label-bold": ["14px", { lineHeight: "18px", fontWeight: "600" }],
        caption: ["12px", { lineHeight: "16px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};